version: "3.9"

services:
  cai:
    build:
      context: .
      dockerfile: ubuntu22.04.dockerfile
    container_name: cai

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    shm_size: "64g"

    volumes:
      - /dev/shm:/dev/shm
      - ~/Navigation:/workspace

    tty: true
    stdin_open: true
    command: /bin/bash
