project_name: nomad-mamba
run_name: nomad

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 256
eval_batch_size: 256
epochs: 200
gpu_ids: [0]
num_workers: 12
lr: 1e-4
optimizer: adamw
clipping: True
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 10
cyclic_period: 0
plateau_patience: 0
plateau_factor: 0.5
seed: 0

# model params
model_type: nomad
vision_encoder: nomad_vint
encoding_size: 256
obs_encoder: efficientnet-b0
attn_unet: False
cond_predict_scale: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]

# diffusion model params
num_diffusion_iters: 10

# mask 
goal_mask_prob: 0.5

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5 # 5
alpha: 1e-4

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 3
  max_dist_cat: 20

# action output params
len_traj_pred: 8
learn_angle: False

# dataset specific parameters
image_size: [96, 96] # width, height

datasets:
  go_stanford:
    data_folder: /workspace/datasets/go_stanford5
    train: vint_train/data/data_splits/go_stanford5/train/
    test: vint_train/data/data_splits/go_stanford5/test/
    end_slack: 0
    goals_per_obs: 2
    negative_mining: True

# datasets:
#   recon:
#     data_folder: /home/czl/nomad_dataset/recon
#     train: /home/czl/data_splits/recon/train/ # path to train folder with traj_names.txt
#     test: /home/czl/data_splits/recon/test/ # path to test folder with traj_names.txt
#     end_slack: 3 # because many trajectories end in collisions
#     goals_per_obs: 1 # how many goals are sampled per observation
#     negative_mining: True # negative mining from the ViNG paper (Shah et al.)
#   go_stanford:
#     data_folder: /home/czl/nomad_dataset/go_stanford_cropped # datasets/stanford_go_new
#     train: /home/czl/data_splits/go_stanford/train/
#     test: /home/czl/data_splits/go_stanford/test/
#     end_slack: 0
#     goals_per_obs: 2 # increase dataset size
#     negative_mining: True
#   cory_hall:
#     data_folder: /home/czl/nomad_dataset/cory_hall/
#     train: /home/czl/data_splits/cory_hall/train/
#     test: /home/czl/data_splits/cory_hall/test/
#     end_slack: 3 # because many trajectories end in collisions
#     goals_per_obs: 1
#     negative_mining: True
#   tartan_drive:
#     data_folder: /home/czl/nomad_dataset/tartan_drive/
#     train: /home/czl/data_splits/tartan_drive/train/
#     test: /home/czl/data_splits/tartan_drive/test/
#     end_slack: 3 # because many trajectories end in collisions
#     goals_per_obs: 1
#     negative_mining: True
#   sacson:
#     data_folder: /home/czl/nomad_dataset/sacson/
#     train: /home/czl/data_splits/sacson/train/
#     test: /home/czl/data_splits/sacson/test/
#     end_slack: 3 # because many trajectories end in collisions
#     goals_per_obs: 1
#     negative_mining: True
  # private datasets (uncomment if you have access)
  # seattle:
  #   data_folder: /home/czl/nomad_dataset/seattle/
  #   train: /home/czl/data_splits/seattle/train/
  #   test: /home/czl/data_splits/seattle/test/
  #   end_slack: 0
  #   goals_per_obs: 1
  #   negative_mining: True
  # scand:
  #   data_folder: /home/czl/nomad_dataset/scand/
  #   train: /home/czl/data_splits/scand/train/
  #   test: /home/czl/data_splits/scand/test/
  #   end_slack: 0
  #   goals_per_obs: 1
  #   negative_mining: True

# logging stuff
## =0 turns off
print_log_freq: 500 # in iterations
image_log_freq: 5000 #0 # in iterations
num_images_log: 8 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.25
wandb_log_freq: 50 # in iterations
eval_freq: 1 # in epochs